<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerOpJtpoJ\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerOpJtpoJ/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerOpJtpoJ.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerOpJtpoJ\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerOpJtpoJ\App_KernelDevDebugContainer([
    'container.build_hash' => 'OpJtpoJ',
    'container.build_id' => 'e56d347a',
    'container.build_time' => 1715273721,
    'container.runtime_mode' => \in_array(\PHP_SAPI, ['cli', 'phpdbg', 'embed'], true) ? 'web=0' : 'web=1',
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerOpJtpoJ');
